# Generated by Django 3.2.20 on 2023-10-03 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_transporter', '0002_alter_fuel_purchased_details_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuel_purchased_details',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
