# Generated by Django 3.2.20 on 2023-08-13 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeration',
            name='phone_number',
            field=models.IntegerField(default=0),
        ),
    ]
