# Generated by Django 3.2.20 on 2023-10-03 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeration',
            name='role',
            field=models.CharField(choices=[('Manager', 'Manager'), ('Fuel_Attendant', 'Fuel Attendant'), ('Fuel_Transporter', 'Fuel Transporter')], default='None', max_length=200),
        ),
    ]
