# Generated by Django 3.2.20 on 2023-10-20 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20231018_0900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='action',
        ),
        migrations.AddField(
            model_name='attendance',
            name='has_clocked_in',
            field=models.BooleanField(default=False),
        ),
    ]
