# Generated by Django 3.2.20 on 2023-08-24 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meter_reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('opening_time', models.TimeField()),
                ('opening_litter', models.IntegerField(default=0)),
                ('closing_time', models.TimeField(blank=True)),
                ('closing_litter', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now=True)),
                ('total_sale', models.IntegerField(default=0)),
            ],
        ),
    ]
