# Generated by Django 3.2.20 on 2023-08-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_attendant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meter_reading',
            name='closing_litter',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='meter_reading',
            name='closing_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meter_reading',
            name='date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='meter_reading',
            name='total_sale',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
