# Generated by Django 3.2.20 on 2023-08-30 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_attendant', '0002_auto_20230824_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='meter_reading',
            name='meter_number',
            field=models.IntegerField(default=0),
        ),
    ]
