# Generated by Django 3.2.20 on 2023-08-31 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_attendant', '0003_meter_reading_meter_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='meter_reading',
            name='fuel_type',
            field=models.CharField(choices=[('Diesel', 'Diesel'), ('Super', 'Super')], default='None', max_length=200),
        ),
    ]
