# Generated by Django 3.2.20 on 2023-10-03 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_attendant', '0005_meter_reading_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meter_reading',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
