# Generated by Django 3.2.20 on 2023-08-30 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fuel_dipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('diesel_dipping', models.IntegerField()),
                ('super_dipping', models.IntegerField()),
                ('date_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
