# Generated by Django 3.2.20 on 2023-08-31 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daily_statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('meter1_opening_reading', models.IntegerField(default=0)),
                ('meter1_opening_time', models.TimeField(default=0)),
                ('meter1_closing_reading', models.IntegerField(default=0)),
                ('meter1_closing_time', models.TimeField(default=0)),
                ('meter1_amount_sold', models.IntegerField(default=0)),
                ('meter2_opening_reading', models.IntegerField(default=0)),
                ('meter2_opening_time', models.TimeField(default=0)),
                ('meter2_closing_reading', models.IntegerField(default=0)),
                ('meter2_closing_time', models.TimeField(default=0)),
                ('meter2_amount_sold', models.IntegerField(default=0)),
                ('diesel_litters_sold', models.IntegerField(default=0)),
                ('diesel_amount_sold', models.IntegerField(default=0)),
                ('diesel_dipping', models.IntegerField(default=0)),
                ('diesel_variance', models.IntegerField(default=0)),
                ('super_litters_sold', models.IntegerField(default=0)),
                ('super_amount_sold', models.IntegerField(default=0)),
                ('super_dipping', models.IntegerField(default=0)),
                ('super_variance', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Monthly_statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DateField()),
                ('diesel_dipping', models.IntegerField()),
                ('super_dipping', models.IntegerField()),
                ('diesel_litter_sold', models.IntegerField()),
                ('super_litter_sold', models.IntegerField()),
                ('diesel_amount_sold', models.IntegerField()),
                ('super_amount_sold', models.IntegerField()),
                ('diesel_variance', models.IntegerField()),
                ('super_variance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Weekly_statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DateField()),
                ('diesel_dipping', models.IntegerField()),
                ('super_dipping', models.IntegerField()),
                ('diesel_litter_sold', models.IntegerField()),
                ('super_litter_sold', models.IntegerField()),
                ('diesel_amount_sold', models.IntegerField()),
                ('super_amount_sold', models.IntegerField()),
                ('diesel_variance', models.IntegerField()),
                ('super_variance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Yearly_statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DateField()),
                ('diesel_dipping', models.IntegerField()),
                ('super_dipping', models.IntegerField()),
                ('diesel_litter_sold', models.IntegerField()),
                ('super_litter_sold', models.IntegerField()),
                ('diesel_amount_sold', models.IntegerField()),
                ('super_amount_sold', models.IntegerField()),
                ('diesel_variance', models.IntegerField()),
                ('super_variance', models.IntegerField()),
            ],
        ),
    ]
