# Generated by Django 3.2.20 on 2023-10-03 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_daily_statistics_monthly_statistics_weekly_statistics_yearly_statistics'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fuel_prices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diesel', models.IntegerField(default=0)),
                ('superfuel', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
