# Generated by Django 3.2.20 on 2023-10-04 10:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_auto_20231004_0637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthly_statistics',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='weekly_statistics',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='yearly_statistics',
            name='duration',
        ),
        migrations.AddField(
            model_name='monthly_statistics',
            name='end_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='monthly_statistics',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='weekly_statistics',
            name='end_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='weekly_statistics',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='yearly_statistics',
            name='end_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='yearly_statistics',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
